/*
 * IBM Confidential
 * OCO Source Materials
 * © Copyright IBM Corp. 2002, 2023
 * The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.
 */

package com.guardium.data;


//import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;



//import org.apache.torque.TorqueException;
//import org.apache.torque.om.Persistent;
//import org.apache.torque.util.Criteria;

//import com.guardium.data.SeverityDesc;
import com.guardium.data.DatasourceType;
import com.guardium.data.AssessmentTest;
import com.guardium.data.AvailableTest;
import com.guardium.map.AssessmentTestMap;
import com.guardium.map.AvailableTestMap;
//import com.guardium.map.SecurityAssessmentMap;
import com.guardium.map.SqlbasedAssessmentDefinitionMap;
//import com.guardium.utils.AdHocLogger;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Nov 05 11:53:20 EST 2003]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class AssessmentTest

{
	
	AvailableTestMap AvailableTestPeer = AvailableTestMap.getAvailableTestMapObject();
	
	/*
	 * mysql> desc ASSESSMENT_TEST;
+-----------------------+-------------+------+-----+---------+----------------+
| Field                 | Type        | Null | Key | Default | Extra          |
+-----------------------+-------------+------+-----+---------+----------------+
| ASSESSMENT_TEST_ID    | int(11)     | NO   | PRI | NULL    | auto_increment |
| ASSESSMENT_ID         | int(11)     | NO   |     | 0       |                |
| TEST_ID               | int(11)     | NO   |     | 0       |                |
| MODIFIED_FLAG         | int(11)     | NO   |     | 0       |                |
| THRESHOLD_VALUE       | float       | YES  |     | NULL    |                |
| SEVERITY              | varchar(60) | NO   |     | INFO    |                |
| EXCEPTIONS_GROUP_ID   | int(11)     | NO   |     | -1      |                |
| SKIP_ERROR_DB_IN_LOOP | int(11)     | NO   |     | 0       |                |
+-----------------------+-------------+------+-----+---------+----------------+
	 * 
	 * 
	 */
	
	public AssessmentTest (int ass_t_id, int ass_id, int t_id, boolean mflag, float t_value, String sev_str, int group_id, boolean skip) {
	    assessment_test_id = ass_t_id;
	    assessment_id = ass_id;
	    test_id = t_id;
	    modified_flag = mflag;
	    threshold_value = t_value;
	    severity = sev_str;
	    exceptions_group_id = group_id;
	    skip_error_db_in_loop = skip;
	}
	
    /**
     * The value for the assessment_test_id field
     */
    private int assessment_test_id;
          
    /**
     * The value for the assessment_id field
     */
    private int assessment_id;
          
    /**
     * The value for the test_id field
     */
    private int test_id;
          
    /**
     * The value for the modified_flag field
     */
    private boolean modified_flag;
          
    /**
     * The value for the threshold_value field
     */
    private double threshold_value;
                                                                                  
    /**
     * The value for the severity field
     */
    private String severity = "INFO";
                                                                        
    /**
     * The value for the exceptions_group_id field
     */
    private int exceptions_group_id = -1;
                                                                                                          
    /**
     * The value for the skip_error_db_in_loop field
     */
    private boolean skip_error_db_in_loop = false;
  
    
    private SecurityAssessment aSecurityAssessment;

    private AvailableTest aAvailableTest;
    
    /**
     * Get the AssessmentTestId
     *
     * @return int
     */
    public int getAssessmentTestId()
    {
        return assessment_test_id;
    }

                                        
    /**
     * Set the value of AssessmentTestId
     *
     * @param v new value
     */
    public void setAssessmentTestId(int v) 
    {
    	this.assessment_test_id = v;          
    }

    /**
     * Get the AssessmentId
     *
     * @return int
     */
    public int getAssessmentId()
    {
        return assessment_id;
    }

                                                  
    /**
     * Set the value of AssessmentId
     *
     * @param v new value
     */
    public void setAssessmentId(int v)
    {
    	if (this.assessment_id != v)
    	{
    		this.assessment_id = v;

    	}
                                      
        if (aSecurityAssessment != null && !(aSecurityAssessment.getAssessmentId()==v))
        {
        	aSecurityAssessment = null;
        }
      
    }


    /**
     * Get the TestId
     *
     * @return int
     */
    public int getTestId()
    {
        return test_id;
    }

                                                  
    /**
     * Set the value of TestId
     *
     * @param v new value
     */
    public void setTestId(int v)
    {
    	test_id = v;
    }

    /**
     * Get the ModifiedFlag
     *
     * @return boolean
     */
    public boolean getModifiedFlag()
    {
        return modified_flag;
    }

                                        
    /**
     * Set the value of ModifiedFlag
     *
     * @param v new value
     */
    public void setModifiedFlag(boolean v) 
    {      
    	this.modified_flag = v;   
    }


    /**
     * Get the ThresholdValue
     *
     * @return double
     */
    public double getThresholdValue()
    {
        return threshold_value;
    }

                                        
    /**
     * Set the value of ThresholdValue
     *
     * @param v new value
     */
    public void setThresholdValue(double v) 
    {
    	this.threshold_value = v;   
    }


    /**
     * Get the Severity
     *
     * @return String
     */
    public String getSeverity()
    {
        return severity;
    }

                                        
    /**
     * Set the value of Severity
     *
     * @param v new value
     */
    public void setSeverity(String v) 
    {
    	this.severity = v;
    }


    /**
     * Get the ExceptionsGroupId
     *
     * @return int
     */
    public int getExceptionsGroupId()
    {
        return exceptions_group_id;
    }

                                        
    /**
     * Set the value of ExceptionsGroupId
     *
     * @param v new value
     */
    public void setExceptionsGroupId(int v) 
    {
    	this.exceptions_group_id = v;
     }


    /**
     * Get the SkipErrorDbInLoop
     *
     * @return boolean
     */
    public boolean getSkipErrorDbInLoop()
    {
        return skip_error_db_in_loop;
    }

                                        
    /**
     * Set the value of SkipErrorDbInLoop
     *
     * @param v new value
     */
    public void setSkipErrorDbInLoop(boolean v) 
    {
    	this.skip_error_db_in_loop = v;        
    }

    /**
     * Declares an association between this object and a SecurityAssessment object
     *
     * @param v SecurityAssessment
     * @
     */
    public void setSecurityAssessment(SecurityAssessment v) 
    {
    	if (v == null)
    	{
    		setAssessmentId(0);
        }
    	else
    	{
    		setAssessmentId(v.getAssessmentId());
    	}
    	aSecurityAssessment = v;
    }

             
    /**
     * Get the associated SecurityAssessment object
     *
     * @return the associated SecurityAssessment object
     * @
     */
    public SecurityAssessment getSecurityAssessment() 
    {
    	
        
    	//if (aSecurityAssessment == null && (this.assessment_id > 0))
    	//{
    	//	aSecurityAssessment = SecurityAssessmentList(this.assessment_id);
  
        /* The following can be used instead of the line above to
           guarantee the related object contains a reference
           to this object, but this level of coupling
           may be undesirable in many circumstances.
           As it can lead to a db query with many results that may
           never be used.
           SecurityAssessment obj = SecurityAssessmentPeer.retrieveByPK(this.assessment_id);
           obj.addAssessmentTests(this);
         */
    	//}
    	return aSecurityAssessment;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey.  e.g.
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setSecurityAssessmentKey(int key) 
    {
    	setAssessmentId(key);
    }     



    /**
     * Declares an association between this object and a AvailableTest object
     *
     * @param v AvailableTest
     * @
     */
    public void setAvailableTest(AvailableTest v) 
    {
    	if (v == null)
    	{
    		setTestId(0);
        }
    	else
    	{
    		setTestId(v.getTestId());
    	}
       aAvailableTest = v;
    }

             
    /**
     * Get the associated AvailableTest object
     *
     * @return the associated AvailableTest object
     * @
     */
    public AvailableTest getAvailableTest() 
    {
    	if (aAvailableTest == null && (this.test_id > 0))
    	{
    		aAvailableTest = AvailableTestPeer.retrieveByPK(this.test_id);
  
    		/* The following can be used instead of the line above to
           guarantee the related object contains a reference
           to this object, but this level of coupling
           may be undesirable in many circumstances.
           As it can lead to a db query with many results that may
           never be used.
           AvailableTest obj = AvailableTestPeer.retrieveByPK(this.test_id);
           obj.addAssessmentTests(this);
         */
    	}
    	return aAvailableTest;
	}

	/**
    * Provides convenient way to set a relationship based on a
    * ObjectKey.  e.g.
    * <code>bar.setFooKey(foo.getPrimaryKey())</code>
    *
    */
    
    /*
    public void setAvailableTestKey(ObjectKey key) 
    {

    	setTestId(((NumberKey) key).intValue());
    }
	*/
    

    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
    	if (fieldNames == null)
    	{
    		fieldNames = new ArrayList<String>();
    		fieldNames.add("AssessmentTestId");
    		fieldNames.add("AssessmentId");
    		fieldNames.add("TestId");
    		fieldNames.add("ModifiedFlag");
    		fieldNames.add("ThresholdValue");
    		fieldNames.add("Severity");
    		fieldNames.add("ExceptionsGroupId");
    		fieldNames.add("SkipErrorDbInLoop");
    		fieldNames = Collections.unmodifiableList(fieldNames);
    	}
    	return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("AssessmentTestId"))
        {
        	return new Integer(getAssessmentTestId());
        }
        if (name.equals("AssessmentId"))
        {
        	return new Integer(getAssessmentId());
        }
        if (name.equals("TestId"))
        {
        	return new Integer(getTestId());
        }
        if (name.equals("ModifiedFlag"))
        {
        	return new Boolean(getModifiedFlag());
        }
        if (name.equals("ThresholdValue"))
        {
        	return new Double(getThresholdValue());
        }
        if (name.equals("Severity"))
        {
        	return getSeverity();
        }
        if (name.equals("ExceptionsGroupId"))
        {
        	return new Integer(getExceptionsGroupId());
        }
        if (name.equals("SkipErrorDbInLoop"))
        {
        	return new Boolean(getSkipErrorDbInLoop());
        }
        return getTableInfoByName(name);
    }
    
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
        	return new Integer(getAssessmentTestId());
        }
        if (pos == 1)
        {
        	return new Integer(getAssessmentId());
        }
        if (pos == 2)
        {
        	return new Integer(getTestId());
        }
        if (pos == 3)
        {
        	return new Boolean(getModifiedFlag());
        }
        if (pos == 4)
        {
        	return new Double(getThresholdValue());
        }
        if (pos == 5)
        {
        	return getSeverity();
        }
        if (pos == 6)
        {
        	return new Integer(getExceptionsGroupId());
        }
        if (pos == 7)
        {
        	return new Boolean(getSkipErrorDbInLoop());
        }
        return null;
    }

			    				   	 										       	 		 			        				   	 		 		    							    			        				   	 		 				    							    		   	        				   	 		 				    			 			        				   		 				    			 			        							 		 				    			 			        						 		 				    			 		   	        						 		 				    			    
    /**
     * Retrieves a String describing some piece of the table, 
     * based on the passed-in name
     *
     * @param name 
     * @return value or null
     */
    private Object getTableInfoByName(String name)
    {
    	if (name.equals("TABLETableName"))
    	{
    		return "ASSESSMENT_TEST";
    	}
    	if (name.equals("TABLETableDefinition"))
    	{
    		return "( ASSESSMENT_TEST_ID INTEGER NOT NULL AUTO_INCREMENT,  ASSESSMENT_ID INTEGER NOT NULL,  TEST_ID INTEGER NOT NULL,  MODIFIED_FLAG INTEGER(1) NOT NULL,  THRESHOLD_VALUE FLOAT,  SEVERITY VARCHAR(60) DEFAULT 'INFO' NOT NULL,  EXCEPTIONS_GROUP_ID INTEGER DEFAULT '-1' NOT NULL,  SKIP_ERROR_DB_IN_LOOP INTEGER(1) DEFAULT '0' NOT NULL, PRIMARY KEY(ASSESSMENT_TEST_ID),  FOREIGN KEY (ASSESSMENT_ID) REFERENCES SECURITY_ASSESSMENT (ASSESSMENT_ID), FOREIGN KEY (TEST_ID) REFERENCES AVAILABLE_TEST (TEST_ID))";
    	}
    	else if (name.equals("TABLETimestampColumn"))
    	{
    		return "";
    	}
    	else if (name.equals("TABLESelectStar"))
    	{
    		return " ASSESSMENT_TEST_ID,  ASSESSMENT_ID,  TEST_ID,  MODIFIED_FLAG,  THRESHOLD_VALUE,  SEVERITY,  EXCEPTIONS_GROUP_ID,  SKIP_ERROR_DB_IN_LOOP";
    	}
    	else if (name.equals("TABLESelectFields"))
    	{
    		return " ASSESSMENT_ID,  TEST_ID,  MODIFIED_FLAG,  THRESHOLD_VALUE,  SEVERITY,  EXCEPTIONS_GROUP_ID,  SKIP_ERROR_DB_IN_LOOP";
    	}
    	else if (name.equals("TABLEPrimaryKey"))
    	{
    		return "ASSESSMENT_TEST_ID";
    	}
    	return null;
    }
 



    /** flag to prevent endless save loop, if this object is referenced
    	by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @
     */

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    /*
    public AssessmentTest copy() 
    {
    	return copyInto(new AssessmentTest());
    }

    protected AssessmentTest copyInto(AssessmentTest copyObj) 
    {
    	copyObj.setAssessmentTestId(assessment_test_id);
    	copyObj.setAssessmentId(assessment_id);
    	copyObj.setTestId(test_id);
    	copyObj.setModifiedFlag(modified_flag);
    	copyObj.setThresholdValue(threshold_value);
    	copyObj.setSeverity(severity);
    	copyObj.setExceptionsGroupId(exceptions_group_id);
    	copyObj.setSkipErrorDbInLoop(skip_error_db_in_loop);

    	//copyObj.setNew(false);
    	//copyObj.setNew(true);
    	copyObj.setAssessmentTestId(0);
        return copyObj;
    }
	*/
    
	private boolean saveThresholdAsDefault = false;
	private boolean saveSeverityAsDefault = false;

	/**
	 * When an Assessment's tests are listed in the gui, they each have a checkbox
	 * alongside for selecting multiple tests for an action (like delete selected).  This
	 * attribute for supporting the checkbox does not in good MVC fashion belong
	 * here in the datamodel, but following AccessRule and taking a shortcut for the
	 * time being
	 */
	private boolean selected = false;

	/**
	 * @return TRUE if the {@link AssessmentTest} was selected (checkbox checked)
	 * in the form, FALSE otherwise
	 */
	public boolean isSelected() {
		return this.selected;
	}

	/**
	 * @param selected - the value to set, TRUE if the {@link AssessmentTest} was
	 * selected (checkbox checked) in the form.
	 */
	public void setSelected(boolean selected) {
		this.selected = selected;
	}

	public boolean isDeprecated() {
		return getAvailableTest().getClassName().contains("DeprecatedTest");
	}
	
	/*
	 * this method is here only to satisfy struts
	 */
	public void setDeprecated(boolean b)
	{
		throw new UnsupportedOperationException();
	}
	/**
	 * @return Our severity's user-display string
	 */

	/*
	public String getSeverityLabel() {
		return Severity.findByValue(this.getSeverity()).getLabel();
	}
	*/

	/**
	 * @return The list of Test Results for this test.
	 * @
	 */


	/**
	 * @return Whether this test is in the "observed category.
	 */
	/*
	public boolean isObservedTest() {
		boolean result = false;

		AvailableTest test = this.getAvailableTest();
		if (test != null) {
			result = test.isObservedTest();
		}

		return result;
	}
	*/
	

	/**
	 * @return Whether this test gathers its data using a jdbc connection.
	 */
	public boolean isJdbcTest() {
		boolean result = false;
		AvailableTest test = this.getAvailableTest();
		if (test != null) {
			result = test.isJdbcTest();
		}

		return result;
	}

	public boolean isCveTest() {
		boolean result = false;
		AvailableTest test = this.getAvailableTest();
		if (test != null) {
			result = test.isCveTest();
		}
		return result;
	}
/*	
	public boolean isAPARTest() 
	{
		boolean result = false;

		AvailableTest test = this.getAvailableTest();
		if (test != null) {
			result = test.isAPARTest();
		}

		return result;
	}
*/
	/**
	 * @return Whether this test uses CAS to aquire its data.
	 */
	/*
	public boolean isCasTest() {
		boolean result = false;

		AvailableTest test = this.getAvailableTest();
		if (test != null) {
			result = test.isCasTest();
		}

		return result;
	}
	*/
	
	/**
	 * @return Whether this test is in the "observed" category;
	 */
	public boolean isQueryBasedTest() {
		boolean result = false;

		AvailableTest test = this.getAvailableTest();
		if (test != null) {
			result = test.isQueryBasedTest();
		}

		return result;
	}


	/**
	 * @return Whether the available test that backs this assessment test uses a datasource.
	 */
	public boolean usesDatasource() {
		boolean result = false;

		AvailableTest test = this.getAvailableTest();
		if (test != null) {
			int typeId = test.getDatasourceTypeId();
			result = typeId > 0;
		}

		return result;
	}

	/**
	 * @return Whether the available test that backs this assessment test uses a datasource.
	 */
	public boolean usesReport() {
		boolean result = false;
		AvailableTest test = this.getAvailableTest();
		if (test != null) {
			int typeId = test.getReportId();
			result = typeId > 0;
		}

		return result;
	}

	@Override
	public String toString() {
		return String.valueOf( this.getAvailableTest() );
	}

	/**
	 * @return The datasource type for this test.
	 */
	public DatasourceType getDatasourceType() {
		DatasourceType type = null;

		type = this.getAvailableTest().getDatasourceType();

		return type;
	}

	public boolean isSeveritySaveAsDefault() {
		return saveSeverityAsDefault;
	}

	public void setSeveritySaveAsDefault(boolean saveAsDefault) {
		this.saveSeverityAsDefault = saveAsDefault;
	}

	public boolean isThresholdSaveAsDefault() {
		return saveThresholdAsDefault;
	}

	public void setThresholdSaveAsDefault(boolean saveAsDefault) {
		this.saveThresholdAsDefault = saveAsDefault;
	}

	public SqlbasedAssessmentDefinition getSqlbasedAssessmentDefinition() {
		SqlbasedAssessmentDefinition result = null;
		SqlbasedAssessmentDefinitionMap SqlbasedAssessmentDefinitionPeer = SqlbasedAssessmentDefinitionMap.getSqlbasedAssessmentDefinitionMapObject();
		
		if (isQueryBasedTest()) {
			result = SqlbasedAssessmentDefinitionPeer.findByTestId(getTestId());
		}
		
		return result;
	}
	
	public void dump() {
		System.out.println("assessment test id: " + this.getAssessmentTestId());
		System.out.println("assessment id: " + this.getAssessmentId());
		System.out.println("test id: " + this.getTestId());
		System.out.println("assessment modified flag: " + this.getModifiedFlag());
		System.out.println("assessment threshold value: " + this.getThresholdValue());
		System.out.println("assessment severity: " + this.getSeverity());
		System.out.println("assessment exception goup id: " + this.getExceptionsGroupId());
		System.out.println("assessment skip_error_db_in_loop: " + skip_error_db_in_loop);
		//System.out.println("assessment exception goup id: " + this.get);
		//System.out.println("assessment exception goup id: " + this.get);
	}
	
	public void save() {
		AssessmentTestMap AssessmentTestPeer = AssessmentTestMap.getAssessmentTestMapObject();
		AssessmentTestPeer.add(this);
	}
}
