/*
 * IBM Confidential
 * OCO Source Materials
 * © Copyright IBM Corp. 2002, 2023
 * The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.
 */
package com.guardium.assessment.tests;

import java.util.Date;

import com.guardium.assessment.tests.TestScore;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Apr 13 12:49:34 EDT 2007]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class TestScoreDefinition
{

	/** Constant value for Test Score result */
	public static final int SCORE_PASS = TestScore.PASS.getScoreValue();
	/** Constant value for Test Score result */
	public static final int SCORE_FAIL = TestScore.FAIL.getScoreValue();
	/** Constant value for Test Score result */
	public static final int SCORE_ERROR = TestScore.ERROR.getScoreValue();
	/** Constant value for Test Score result */
	public static final int SCORE_NO_CAS_DATA = TestScore.NO_CAS_DATA.getScoreValue();
	/** Constant value for Test Score result */
	public static final int SCORE_NO_REPORT_DATA = TestScore.NO_REPORT_DATA.getScoreValue();
	/** Constant value for Test Score result */
	public static final int SCORE_UNSUPPORTED_DB_VERSION = TestScore.UNSUPPORTED_DB_VERSION.getScoreValue();
	/** Constant value for Test Score result */
	public static final int SCORE_UNSUPPORTED_OS_VERSION = TestScore.UNSUPPORTED_OS_VERSION.getScoreValue();
	/** Constant value for Test Score result */
	public static final int SPECIAL_ERROR = TestScore.SPECIAL_ERROR.getScoreValue();
	/** The Pre Test Check Failed Test Not Executed. */ 
	public static final int PRE_TEST_CHECK_FAILED = TestScore.PRE_TEST_CHECK_FAILED.getScoreValue();
	/** The calculateScore is not defined */
	public static final int EXECUTION_TEST_ROUTINE_CHECK_FAILED = TestScore.EXECUTION_TEST_ROUTINE_CHECK_FAILED.getScoreValue();

	public static final int UNSUPPORT_CVE_PATCH_DETECTED = TestScore.UNSUPPORT_CVE_PATCH_DETECTED.getScoreValue();

	
	/** Unsupported Security PTF patch detected **/
	public static final int UNSUPPORT_PTF_PATCH_DETECTED = TestScore.UNSUPPORT_PTF_PATCH_DETECTED.getScoreValue();	
	
	/*
	public TestScoreDefinition () {
		
	}
	*/
	
	public TestScoreDefinition (int score, String desc, Date ts) {
		test_score = score;
		description = desc;
		timestamp = ts;
	}	
	
	private int test_score;
	private String description;
	private Date timestamp;
	
	
	public int getTestScore() {
		return test_score;
	}
	public void setTestScore(int test_score) {
		this.test_score = test_score;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Date getTimestamp() {
		return timestamp;
	}
	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	
	
	
	
}
