/*
 * IBM Confidential
 * OCO Source Materials
 * © Copyright IBM Corp. 2002, 2023
 * The source code for this program is not published or otherwise divested of its trade secrets, irrespective of what has been deposited with the U.S. Copyright Office.
 */
package com.guardium.utils;

import java.io.File;
import java.io.FileInputStream;


import com.guardium.utils.i18n.Say;

public class DispalyPdfFile {

	public static final String PDF = "application/pdf";
	public static final String PLAIN_TEXT = "text/plain";
	public static final String ZIP = "application/zip";
	public static final String ROOT = System.getProperty("webappRoot") ;
	private static final String JAVA_HOME = System.getProperty("java.home") ;
	private static final String CLASS_PATH = System.getProperty("java.class.path");
	private static final String PD4ML_JAR = ROOT + "WEB-INF/lib/pd4ml.jar";
	private static final String CSS_JAR = ROOT + "WEB-INF/lib/ss_css2.jar";
	private static final File WORKING_DIR_FILE = new File(ROOT + "WEB-INF/conf");
	private static final String JAVA_OPTIONS = "-Xmx1024m";
	

	
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}


/**
 * Given the full filepath of both html and pdf, create a pdf from the html file
 * 
 * @param html	a <strong>String</strong>: the full filepath of the input html file
 * @param pdf		a <strong>String</strong>: the full filepath of the created pdf file
 * @param regenerate if <em>true</em>, regenerate the file if it already exists
 * @throws Exception
 */
public static void createPdfFromHtml(String html, String pdf, boolean regenerate) 
throws Exception {
//	String html = getHtmlFileName(baseName);
//	String pdf = getPdfFileName(baseName);
	// check to see if the pdf exists, since the names are unique
	File pdfFile = new File(pdf);
	if (regenerate || !pdfFile.exists() ) {
		String [] cmdArr = {
				JAVA_HOME + "/bin/java", JAVA_OPTIONS,  "-jar", PD4ML_JAR,  "file://" +html, pdf
		};
		
		StringBuffer sb = new StringBuffer();			
		boolean success = executeCommand(cmdArr, null, WORKING_DIR_FILE, sb);
		if (!success) {
			String msg = "Unable to create PDF file due to execution problem:" + Say.NL + sb;
			throw new Exception(msg);
		}
		
		if (sb.length() != 0) {
			String msg = 
				"Create Pdf From Html. Received the following process information when converting " 
				+ html + " to " + pdf +": \n" + sb
			;
			AdHocLogger.logDebug(msg, AdHocLogger.LOG_DEBUG);
		}
	}
}

/**
 *   Execute a command-line command.  Puts anything written by the executed command,
 *  either the stdout or stderr into the input StringBuffer.  
 * 
 * @param commandArr		A <strong>String[]</strong> containing each token of the command to be executed
 * @param envp						<strong>null</strong>or a  <strong>String[]</strong> of environmental parameters. Each element of which has environment variable settings in format <i>name=value.</i>
 * @param dir							<strong> null</strong> or a <strong>File</strong> of the directory in which to run the command/
 * @param sb							<strong>StringBuffer</strong> to contain any stdout or stderr generated by the process.
 * @return <i>true</i> if the command-line status is 0, <i>false</i> otherwise
 * @throws Exception
 */
static public boolean executeCommand(String [] commandArr, String[] envp, File dir,StringBuffer sb) throws Exception 
{
    return Utils.executeCommand(commandArr, envp, dir, sb, null,null);
}


/**
 *  Given the input <strong>HttpServletResponse</strong>, bare file name 
 *  (e.g. <i>foo_1.pdf</i>), and full File Path, 'download' the file
 * 
 * @param response
 * @param baseName
 * @param fullFilePath
 * @param contentType 	a <strong>String</strong> to put in the response header's ContentType field (e.g.: <i>application/pdf</i>
 * @throws Exception
 */

/*
	public static void downloadBinaryFile(HttpServletResponse response, String binFileName, String fullFilePath, String contentType)
	throws Exception
	{

		response.setContentType(contentType);
		response.setHeader("Content-Disposition","attachment; filename=" + binFileName);

		ServletOutputStream sos = response.getOutputStream();
		sos.flush();
		File inputFile = new File(fullFilePath);
		FileInputStream in = new FileInputStream(inputFile);

		byte[] buffer = new byte[4097];
		int res;	
		while((res=in.read(buffer,0,4096))>0)
			sos.write(buffer,0,res); 
		in.close();
	}	
*/

/*
	public ActionForward download(
			ActionMapping mapping,
			ActionForm form,
			HttpServletRequest request,
			HttpServletResponse response) throws Exception 
		{
			MustGatherResultsForm aform = (MustGatherResultsForm) form;
			File toDownload = new File(aform.getPath());
			if (toDownload!=null && toDownload.isFile()) {
				DynamicFileUtil.downloadBinaryFile(response, toDownload.getName(), toDownload.getAbsolutePath(), "application/octet-stream");
			}
			return mapping.findForward("this");
		}
	
 * 
 */
}